services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # environment:
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_NAME=${DB_NAME}
    #   - DB_SSLMODE=${DB_SSLMODE}
    #   - JWT_SECRET=${JWT_SECRET}
    #   - SERVER_ADDRESS=${SERVER_ADDRESS}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - pwc-network
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pwc_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pwc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  pwc-network:
    driver: bridge
