# air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe" # Use .exe for Windows
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go" # Point to the correct main.go file
  delay = 1000 # Delay after file changes (in milliseconds)
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "500ms"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = false

[misc]
  clean_on_exit = true